---
# handlers file for apache
- name: Restart_apache
  ansible.builtin.systemd:
    service: apache2
    state: restarted

- name: Enable Apache service to start at boot
  ansible.builtin.systemd:
    service: apache2
    enabled: true